### PR TITLE
Fix #247 CSS classes for jQuery click binding do not work for Django 2.1.3

### LINKED ISSUE #247: CSS classes for jQuery click binding do not work for Django 2.1.3
It seems that .inline-group now needs to be ._inline-group, in static/ajax_select/js/ajax_select.js line 243 (with Django 2.1.3) - otherwise #157 is back.

### PR DESCRIPTION
**Pull request by nwp90**
Fixes #247

### CODE REVIEW

File: ajax_select/static/ajax_select/js/ajax_select.js [hunk 1]
```diff
@@ -240,7 +240,7 @@
     $(window).trigger('init-autocomplete');
     // When adding new rows in inline forms, reinitialize and activate newly added rows.
     $(document)
-      .on('click', '.inline-group ul.tools a.add, .inline-group div.add-row a, .inline-group .tabular tr.add-row td a', function() {
+      .on('click', '._inline-group ul.tools a.add, ._inline-group div.add-row a, ._inline-group .tabular tr.add-row td a', function() {
```
Comment (crucialfelix) [inline ajax_select/static/ajax_select/js/ajax_select.js]: It needs to include both the old classes and the new ones. Only then will it work for all supported versions.

`.inline-group ul.tools a.add, .inline-group div.add-row a, .inline-group .tabular tr.add-row td a, ._inline-group ul.tools a.add, ._inline-group div.add-row a, ._inline-group .tabular tr.add-row td a`

**Comment by crucialfelix** [comment]
Thanks for the PR!
